repository:
    path: github.com/prometheus/alertmanager
crossbuild:
    platforms:
        main:
            - linux/amd64
            - linux/386
            - darwin/amd64
            - darwin/386
            - windows/amd64
            - windows/386
        arm:
            - linux/arm
            - linux/arm64 
        powerpc:
            -
